name: build matrix demo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        include:
          # Django 3.2
          - django-version: "3.2"
            python-version: "3.7"
          - django-version: "3.2"
            python-version: "3.8"
          - django-version: "3.2"
            python-version: "3.9"
          - django-version: "3.2"
            python-version: "3.10"
          # Django 4.1
          - django-version: "4.1"
            python-version: "3.8"
          - django-version: "4.1"
            python-version: "3.9"
          - django-version: "4.1"
            python-version: "3.10"
          - django-version: "4.1"
            python-version: "3.11"
          # Django 4.2
          - django-version: "4.1"
            python-version: "3.8"
          - django-version: "4.1"
            python-version: "3.9"
          - django-version: "4.1"
            python-version: "3.10"
          - django-version: "4.1"
            python-version: "3.11"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Upgrade django version
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Python and Django versions
        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"

